spring:
  application:
    name: resource-server
server:
  port: 8082

security:
  oauth2:
    client:
      client-id: user
      client-secret: 123456
      user-authorization-uri: http://localhost:8081/oauth/authorize
      access-token-uri: http://localhost:8081/oauth/token
    resource:
      id: user
      token-info-uri: http://localhost:8081/oauth/check_token